require "simon.launch"
require "simon.options"
require "simon.keymaps"
require "simon.autocmds"

spec "simon.colorscheme"
spec "simon.treesitter"
spec "simon.whichkey"
spec "simon.telescope"
spec "simon.harpoon"
spec "simon.lualine"
spec "simon.bufferline"
spec "simon.breadcrumbs"
spec "simon.none-ls"
-- spec "simon.copilot"
-- spec "simon.chatgpt"
spec "simon.mason"
spec "simon.nvim-surround"
spec "simon.neogit"
spec "simon.neotest"
spec "simon.gitsigns"
spec "simon.comment"
spec "simon.todo-comments"
spec "simon.autopairs"
spec "simon.indentline"
spec "simon.navic"
spec "simon.illuminate"
spec "simon.toggleterm"
spec "simon.cmp"
spec "simon.lspconfig"
spec "simon.undotree"
spec "simon.colorizer"

spec "simon.obsidian"
spec "simon.web-devicons"
spec "simon.mini-icons"

spec "simon.oil"
-- spec "simon.neorg" -- Note Taking tool
-- spec "simon.markdown"
-- spec "simon.peek"

require "simon.lazy"
