-- Main settings
vim.g.mapleader = " "
vim.g.maplocalleader = " "
require("config.launch")
pcall(require, "local-config") -- Load local config if it exists
require("config.options")
require("config.filetypes")
require("config.globalKeymaps")
require("config.autoCmds")
require("config.lemonade")
require("config.lsp")

-- Other
spec("colorscheme")

-- plugins
spec("plugins.mini-icons")
spec("plugins.mini-ai")
spec("plugins.mini-clue")
spec("plugins.mini-statusline")
spec("plugins.mini-git")
spec("plugins.mini-diff")
spec("plugins.mini-pairs")
spec("plugins.tmux-nav")
spec("plugins.oil")
spec("plugins.mini-pick")
spec("plugins.mini-extra")
spec("plugins.blink-cmp")
spec("plugins.treesitter")
spec("plugins.nvim-ts-autotag")
spec("plugins.undotree")
spec("plugins.copilot")
spec("plugins.kulala")
spec("plugins.obsidian")
spec("plugins.kubectl")
spec("plugins.mason")
spec("plugins.nvim-lspconfig")
spec("plugins.mason-lspconfig")
spec("plugins.mason-tool-installer")
spec("plugins.conform")
spec("plugins.nvim-lint")
spec("plugins.dap")
spec("plugins.image")
spec("plugins.render-markdown")
spec("plugins.vimtex")
spec("plugins.nomad")
-- spec("plugins.triforce")
spec("plugins.typstPreview")

require("config.lazy")
