-- return {
--   "nvimtools/none-ls.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--   },
--   config = function()
--     local null_ls = require("null-ls")
--     local b = null_ls.builtins
--
--     null_ls.setup({
--       sources = {
--         -- Formatters
--         b.formatting.prettier,
--         b.formatting.stylua,
--         b.formatting.black,
--         b.formatting.shfmt,
--         b.formatting.gofumpt,
--         b.formatting.mdformat,
--
--         -- Linters
--         b.diagnostics.yamllint,
--         b.diagnostics.markdownlint,
--         b.diagnostics.golangci_lint,
--         b.diagnostics.buf,
--         b.diagnostics.protolint,
--       },
--       diagnostics_format = "[#{s}] #{m}",
--     })
--   end,
-- }
